// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { env } from '@/lib/env';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// NOTE: Keep client typing permissive until generated types are fully synchronized
// with the live schema/migrations used by this codebase.
export const supabase = createClient(env.VITE_SUPABASE_URL, env.VITE_SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
